### ISSUE TITLE
2020-11-04: 'make check' does not catch entries with no body

### ISSUE THREAD

**Issue by gvwilson** [carpentries/glosario#202]
`glossary.yml` contains:

```
- slug: directory
```

without any definitions in any language. `make check` should flag this as an error.

**Comment by baileythegreen** [comment]
@gvwilson I looked into this. It's because it falls through checks by the linter and is silently dropped by check_glossary.py.

The linter would flag:
```
- slug:           # nothing here


- slug: an_entry
```

check_glossary.py would flag:
```
- slug: entry
    unknown_key:
```

or

```
- slug: entry

-                  # missing the slug key

- slug: another_entry
```

The existing function that could easily catch this is here. My notes inside `**` explain why it fails to catch them:

```
def checkEntry(entry):
    ''' 
    Check structure of individual entries, returning a language-to-set
    dictionary of terms references in the body.
    '''
    keys = set(entry.keys())

** ENTRY_REQUIRED_KEYS is {'slug'} (won't be missing for an entry without a body) **
    missing = [k for k in ENTRY_REQUIRED_KEYS if k not in keys]               
    if missing:
        print(f'Missing required keys for entry {entry}: {missing}')
    slug = entry['slug']
    unknown_keys = keys - ENTRY_KEYS
    if unknown_keys:
        print(f'Unknown keys in {slug}: {unknown_keys}')
    result = {}
    crossrefs = set(entry['ref']) if ('ref' in entry) else set()

** if the entry is empty, it doesn't have any language keys, so it is silently dropped here **
    for lang in ENTRY_LANGUAGE_KEYS:
        if lang in entry:
            label = f'{slug}/{lang}'
            result[lang] = checkLanguageDef(label, crossrefs, entry[lang])
    return result
```

There are different ways this could be solved. An easy one, and the test I used to determine where the bug lay, is to insert: `if keys == {'slug'}: print('Empty entry found')` after `keys = set(entry.keys())`.

However, it is worth clarifying exactly what sort of 'empty entry' is to be avoided and whether there are other checks worth making.
