### ISSUE TITLE
2020-12-01: Add "DRY principle" 

### ISSUE THREAD

**Issue by sstevens2** [carpentries/glosario#234]
We are linking to glossario for the [Jekyll pages lesson](https://carpentries-incubator.github.io/building-websites-with-jekyll-and-github-or-gitlab/reference.html) and thought it might be good to add a definition for the `DRY principle`.  I'm not confident in my definition and would appreciate someone else drafting it. Happy to help or review though.

[Draft PR adding glassario links to glossary page](https://github.com/carpentries-incubator/building-websites-with-jekyll-and-github-or-gitlab/pull/165)

**Comment by baileythegreen** [comment]
@sstevens2 I have drafted one.

The Don't Repeat Yourself (DRY) Principle states that — Every piece of knowledge must have a single, unambiguous, authoritative representation within a system. The term comes from The Pragmatic Programmer, by Andrew Hunt and David Thomas. Programs that follow the DRY Principle avoid duplication of definitions and logic, so that a change in their behaviour only requires each modification to be made in one part of the code. The goal is to create code that is easier to maintain.

**Comment by sstevens2** [comment]
That looks great to me!

**Comment by baileythegreen** [comment]
@sstevens2 Would you like me to make the PR for it? (I've just been added as an editor, and am looking for an excuse to create a PR so I can screenshot my GitHub handle in it.

**Comment by sstevens2** [comment]
Of course!  Please do.  Your definition, you should definitely get credit via the PR.

**Comment by baileythegreen** [comment]
@sstevens2

I wasn't even thinking about the credit (I don't really need it seeing as I'm already the top contributor here, hehe).

I've submitted PR #237 to resolve this.

**Comment by sstevens2** [comment]
My maintainer mentality of wanting the person who did the work to get the credit, I guess. 😆  Your PR looks great to me but I'm not as familiar with the formatting here as I just submitted my first definition yesterday. I'm sure Zhian's review will be more helpful.

**Comment by baileythegreen** [comment]
I'm fairly familiar with the formatting, as my first PR here was a gigantic one just proofreading all of the English entries, but this entry is a bit unusual since it contains an acronym, but has more to it. Thus far, that is not true for any other entry, so we don't really have a way of formatting it.

**Comment by sstevens2** [comment]
Makes sense.  It is an unusual one. Possibly some precedent.

Wow amazing you proofread all the english entries!  Thanks for your hard work!

**Comment by elletjies** [comment]
@all-contributors please add @sstevens2 question

**Comment by elletjies** [comment]
@all-contributors please add @baileythegreen  question

**Comment by elletjies** [comment]
@all-contributors please add @yabellini  question
