### ISSUE TITLE
[22/04/2021]: [Is there interest to include new languages?]

### ISSUE THREAD

**Issue by Eirinits** [carpentries/glosario#285]
I was wondering whether there is interest from the community to include more languages than the existing ones in the glosario. 

Even though it makes sense to include the most spoken languages, languages of smaller countries are many times underrepresented and it is a real struggle finding material translated in these languages. I had in mind translating terms in Greek mainly since it is my mother tongue, but I could also do it in Norwegian. 

I would love to hear what the community thinks!

**Comment by baileythegreen** [comment]
Yes!

Actually, all of the languages we have are because people have come along and added them, it wasn't a choice anyone made; they happen to be the most-spoken ones because they are the most-spoken ones.

The people already here can only contribute languages we know, so we need volunteers from other languages (like you!) who want to contribute in order to expand.

Please, contribute. If you want to add other languages, a good place to start would be looking at the [`_config.yml`](https://github.com/carpentries/glosario/blob/master/_config.yml) file and translating the blurb there into the new language(s).

If you want to do this, you could submit a new issue for each language you wanted to add. Then we can track them separately. We'll have to update some of the infrastructure to add the new languages there, once we have the translated blurb.

I'm going to close this, but you can still comment here, if you need to.

**Comment by elletjies** [comment]
@all-contributors please add @ageorgou question
